### PR TITLE
v2.1.6.post1

### PR DESCRIPTION
**Pull request by kylebgorman**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by kylebgorman** [comment]
@conda-forge-admin, please rerender

**Review by jakirkham — CHANGES_REQUESTED** [review]
CI is not running. Please do not merge until it is resolved

More details in issue: https://github.com/conda-forge/status/issues/184

**Comment by jakirkham** [comment]
@conda-forge-admin , please restart CI

**Comment by jakirkham** [comment]
@conda-forge-admin , please re-render

**Pull request merged**
